function [time,lux,CLA,CS,activity] = importDaysimeter(filename, startRow, endRow)
%IMPORTDAYSIMETER Import Daysimeter data from a text file as column vectors.
%   [TIME,LUX,CLA,CS,ACTIVITY] = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [TIME,LUX,CLA1,CS,ACTIVITY] = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [Time,Lux,CLA1,CS,Activity] =
%   importfile('Subject01_Day72_130404_0537_processed.txt',2, 15528);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/04/05 09:41:46

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
TimeStr = dataArray{:, 1};
time = datenum(TimeStr,'mm/dd/yyyy HH:MM:SS');
lux = dataArray{:, 2};
CLA = dataArray{:, 3};
CS = dataArray{:, 4};
activity = dataArray{:, 5};

